apiVersion: apps/v1
kind: Deployment
metadata:
  name: configserver
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels: { app: configserver }
  template:
    metadata:
      labels: { app: configserver }
    spec:
      containers:
        - name: configserver
          image: aimendocker/configserver@sha256:1239102cfa9c012d4f166732582670af90ac90e4508b2e9abc054e7f09e70707
          ports:
            - containerPort: 8071
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "git"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: "https://github.com/AimenFH/bankapplication-config.git"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_DEFAULT_LABEL
              value: "main"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_CLONE_ON_START
              value: "true"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_FORCE_PULL
              value: "true"
            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_TIMEOUT
              value: "5"
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8071 }
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
  namespace: bank
spec:
  selector: { app: configserver }
  ports:
    - port: 8071
      targetPort: 8071
