services:
  accounts:
    image: "aimendocker/accounts:s4"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aimendocker
  loans:
    image: "aimendocker/loans:s4"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aimendocker
  cards:
    image: "aimendocker/cards:s4"
    container_name: cards-ms
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - aimendocker
networks:
  aimendocker:
    driver: "bridge"


